### ISSUE TITLE
[IMPROVEMENT] > sketch-builder: Dependency cycles.

### ISSUE THREAD

**Issue by ddprrt** [Dynatrace/sketchmine#34]
**Description**
📦  sketch-builder

Lerna is detecting dependency cycles, because `sketch-builder` is requiring itself in `devDependencies`. According to @lukasholzer this is due to Yarn workspaces needing that for binary files. Let's see if we can fix that and still retain all the functionality.

**Comment by lukasholzer** [comment]
fixed in version **[v2.4.0](https://github.com/Dynatrace/sketchmine/releases/tag/v2.4.0)** with commit [d23c408831285b9197fd32ad7de201874c0a5aba](https://github.com/Dynatrace/sketchmine/commit/d23c408831285b9197fd32ad7de201874c0a5aba#diff-ecd7f9c51225ccd6cbcff9f995ead32d)

**Comment by ddprrt** [comment]
🎉
