### ISSUE TITLE
[BUG] > sketch-validator: artboards empty validation throws when it shouldn't

### ISSUE THREAD

**Issue by lukasholzer** [Dynatrace/sketchmine#61]
**Description**
📦 sketch-validator throws artboard empty errors where artboards are not empty.

Some product Sketch files throw artboard empty errors, but the artboards are not empty. (e.g. kubernetes-overview).

Other files throw an artboard-missing error on the symbols page that does not need an artboard (e.g. ci360-home).

[internal Dynatrace issue](https://dev-jira.dynatrace.org/browse/UX-9039)

**Additional context**

**Comment by lara-aigmueller** [comment]
Should be fixed by https://github.com/Dynatrace/sketchmine/pull/62
